apiVersion: apps/v1 
kind: Deployment
metadata:
  name: insurance-app-deployment 
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ins
  template:
    metadata:
      labels:
        app: ins
    spec:
      containers:
      - name: ins-app
        image: muralisocial123/insurance-app-excelr:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: ins-svc 
spec: 
  selector:
    app: ins 
  ports: 
    - port: 80
      targetPort: 80
      protocol: TCP 
  type: LoadBalancer     
          